# Generated by Django 5.1.3 on 2025-07-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
