# Generated by Django 5.1.3 on 2025-07-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_learningmaterial_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningmaterial',
            options={'ordering': ['sequence']},
        ),
    ]
