# Generated by Django 5.1.3 on 2025-07-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_learningmaterial_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningmaterial',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
